theme: jekyll-theme-minimal
title: Browns Data Science
description: Technical Documentation for Data Science & AI Projects
show_downloads: false
google_analytics:

# Plugins for GitHub Pages
plugins:
  - jemoji

# Markdown Configuration
markdown: GFM
# Alternative if GFM doesn't work:
# markdown: CommonMarkGhPages