theme: jekyll-theme-minimal
title: Browns Data Science
description: Technical Documentation for Data Science & AI Projects
show_downloads: false
google_analytics:

# Plugins for GitHub Pages
plugins:
  - jemoji

# Markdown Configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true